version: '3'

services:

  hse:
    image: robix82/usi.ch-hse:0.1
    depends_on:
      - hse-mysql
    ports:
      - "80:8080"
    environment:
      - spring.profiles.active=prod
    restart: always
    networks:
      - hse-network
    volumes:
      - hse-data:/data

  hse-mysql:
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: hse_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - hse-network
    volumes:
      - hse-datavolume:/var/lib/mysql

networks:
  hse-network:

volumes:
  hse-datavolume:
  hse-data:




